### ISSUE TITLE
Install Failed 

### ISSUE THREAD

**Issue by Mtze** [entwicklerstube/mvg-cli#4]
After I installed `mvg` with `npm install mvg-cli -g` and tried to execute it.
 I got:

```
nternal/modules/cjs/loader.js:613
    throw err;
    ^

Error: Cannot find module 'iconv-lite'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:611:15)
    at Function.Module._load (internal/modules/cjs/loader.js:537:25)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/mvg-cli/lib/utils/loadData.js:20:18)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
```

**Comment by greenchapter** [comment]
Same here 😞

**Comment by lostdesign** [comment]
@Mtze @greenchapter checkout [lukaskollmer/mvg-api](https://github.com/lukaskollmer/mvg-node), it also has a CLI version (and is maintained). My PR needs to be merged for it to work again, so you could also either apply the fix yourself meanwhile or use my fork.
